### ISSUE TITLE
document.write prevent lazy loading

### ISSUE THREAD

**Issue by ChrisCinelli** [borisreitman/CrossXHR#2]
The JS could be a little more nice. Ex. Use of closures. document.write is a no no for lazy loading.

**Comment by borisreitman** [comment]
The library is designed to be small, without dependencies. In order to know when to use document.write and when not to requires to know when the document is ready, which is best known with jQuery. I didn't want to ship jQuery with the library.

However, if you always load dynamically, you know that you are already in document ready state, so you can append the two span tags with javascript. 

The line

```
  document.write('<span style="position:absolute;top:0;left:0"><span id="FlashHttpRequest_gateway"></span></span>');
```

can be replaced with: 

```
var n = document.createElement("span"); n.style.position = "absolute" ; n.style.top = "0"; n.style.left = "0";
document.body.appendChild(n);
n.innerHTML = '<span id="FlashHttpRequest_gateway"></span>';
```
